UNPAID_SESSION = {
    "id": "cs_test_a1hcm6rOR4FEc4ClwwfDwJUS6FMLcSX4cVgHOxZi7xyguyFseMa3k5zNcN",
    "object": "checkout.session",
    "after_expiration": None,
    "allow_promotion_codes": None,
    "amount_subtotal": None,
    "amount_total": None,
    "automatic_tax": {"enabled": False, "status": None},
    "billing_address_collection": None,
    "cancel_url": "https://example.com/cancel",
    "client_reference_id": None,
    "consent": None,
    "consent_collection": None,
    "currency": None,
    "customer": None,
    "customer_creation": None,
    "customer_details": None,
    "customer_email": None,
    "expires_at": 1660685280,
    "livemode": False,
    "locale": None,
    "metadata": {},
    "mode": "payment",
    "payment_intent": "pi_1Drabb2eZvKYlo2CRZoK3NG4",
    "payment_link": None,
    "payment_method_collection": None,
    "payment_method_options": {},
    "payment_method_types": ["card"],
    "payment_status": "unpaid",
    "phone_number_collection": {"enabled": False},
    "recovered_from": None,
    "setup_intent": None,
    "shipping_address_collection": None,
    "shipping_cost": None,
    "shipping_details": None,
    "shipping_options": [],
    "status": "expired",
    "submit_type": None,
    "subscription": None,
    "success_url": "https://example.com/success",
    "total_details": None,
    "url": "test_checkout_stripe.stripe.com",
}

PAID_SESSION = {
    "id": "cs_test_a1I4ilEL2HJd6Xd3W3ZPmWaHwK9riDhIExst0tdavkwEoIN8UK9EN6Yklk",
    "object": "checkout.session",
    "livemode": False,
    "payment_intent": "pi_3LWQKBHg7k0wiFiz02Lpvytj",
    "status": "complete",
    "after_expiration": None,
    "allow_promotion_codes": None,
    "amount_subtotal": 300,
    "amount_total": 300,
    "automatic_tax": {"enabled": True, "status": "complete"},
    "billing_address_collection": None,
    "cancel_url": "http://localhost:3000/app/discovery",
    "client_reference_id": "1",
    "consent": None,
    "consent_collection": None,
    "currency": "usd",
    "customer": "cus_MEu8lc7NZySWFU",
    "customer_creation": "always",
    "customer_details": {
        "address": {
            "city": "Austin",
            "country": "US",
            "line1": "3400 Harmon Avenue",
            "line2": None,
            "postal_code": "78705",
            "state": "TX",
        },
        "email": "test@mochajump.com",
        "name": "333",
        "phone": None,
        "tax_exempt": "none",
        "tax_ids": [],
    },
    "customer_email": "test@mochajump.com",
    "expires_at": 1660506527,
    "locale": None,
    "metadata": {"coins": "300"},
    "mode": "payment",
    "payment_link": None,
    "payment_method_collection": "always",
    "payment_method_options": {},
    "payment_method_types": ["card"],
    "payment_status": "paid",
    "phone_number_collection": {"enabled": False},
    "recovered_from": None,
    "setup_intent": None,
    "shipping": None,
    "shipping_address_collection": None,
    "shipping_options": [],
    "shipping_rate": None,
    "submit_type": None,
    "subscription": None,
    "success_url": "http://localhost:3000/app/discovery",
    "total_details": {"amount_discount": 0, "amount_shipping": 0, "amount_tax": 0},
    "url": None,
}

BALANCE_TRANSACTION = {
    "id": "txn_3LVq26Hg7k0wiFiz0BpFMS8B",
    "object": "balance_transaction",
    "amount": 500,
    "available_on": 1660867200,
    "created": 1660280650,
    "currency": "usd",
    "description": None,
    "exchange_rate": None,
    "fee": 45,
    "fee_details": [
        {
            "amount": 45,
            "application": None,
            "currency": "usd",
            "description": "Stripe processing fees",
            "type": "stripe_fee",
        }
    ],
    "net": 455,
    "reporting_category": "charge",
    "source": "ch_3LVq26Hg7k0wiFiz01Cy1kAs",
    "status": "pending",
    "type": "charge",
}

PAYMENT_INTENT = {
    "id": "pi_3LWQKBHg7k0wiFiz02Lpvytj",
    "charges": {
        "object": "list",
        "data": [
            {
                "id": "ch_3LWQKBHg7k0wiFiz0swYpF5z",
                "object": "charge",
                "amount": 300,
                "amount_captured": 300,
                "amount_refunded": 0,
                "application": None,
                "application_fee": None,
                "application_fee_amount": None,
                "balance_transaction": "txn_3LWQKBHg7k0wiFiz01205TmU",
                "billing_details": {
                    "address": {
                        "city": "Austin",
                        "country": "US",
                        "line1": "3400 Harmon Avenue",
                        "line2": None,
                        "postal_code": "78705",
                        "state": "TX",
                    },
                    "email": "test@mochajump.com",
                    "name": "333",
                    "phone": None,
                },
                "calculated_statement_descriptor": "MOCHAJUMP.COM",
                "captured": True,
                "created": 1660420146,
                "currency": "usd",
                "customer": "cus_MEu8lc7NZySWFU",
                "description": None,
                "destination": None,
                "dispute": None,
                "disputed": False,
                "failure_balance_transaction": None,
                "failure_code": None,
                "failure_message": None,
                "fraud_details": {},
                "invoice": None,
                "livemode": False,
                "metadata": {},
                "on_behalf_of": None,
                "order": None,
                "outcome": {
                    "network_status": "approved_by_network",
                    "reason": None,
                    "risk_level": "normal",
                    "risk_score": 26,
                    "seller_message": "Payment complete.",
                    "type": "authorized",
                },
                "paid": True,
                "payment_intent": "pi_3LWQKBHg7k0wiFiz02Lpvytj",
                "payment_method": "pm_1LWQKSHg7k0wiFizEbK2sgEZ",
                "payment_method_details": {
                    "card": {
                        "brand": "visa",
                        "checks": {
                            "address_line1_check": "pass",
                            "address_postal_code_check": "pass",
                            "cvc_check": "pass",
                        },
                        "country": "US",
                        "exp_month": 3,
                        "exp_year": 2033,
                        "fingerprint": "AbWD568b97AY4a2P",
                        "funding": "credit",
                        "installments": None,
                        "last4": "4242",
                        "mandate": None,
                        "network": "visa",
                        "three_d_secure": None,
                        "wallet": None,
                    },
                    "type": "card",
                },
                "receipt_email": None,
                "receipt_number": None,
                "receipt_url": "https://pay.stripe.com/receipts/payment/asdf-Ah",
                "refunded": False,
                "refunds": {
                    "object": "list",
                    "data": [],
                    "has_more": False,
                    "total_count": 0,
                    "url": "/v1/charges/ch_3LWQKBHg7k0wiFiz0swYpF5z/refunds",
                },
                "review": None,
                "shipping": None,
                "source": None,
                "source_transfer": None,
                "statement_descriptor": None,
                "statement_descriptor_suffix": None,
                "status": "succeeded",
                "transfer_data": None,
                "transfer_group": None,
            }
        ],
        "has_more": False,
        "total_count": 1,
        "url": "/v1/charges?payment_intent=pi_3LWQKBHg7k0wiFiz02Lpvytj",
    },
    "client_secret": "pi_3LWQKBHg7k0wiFiz02Lpvytj_secret_tS3XOru3PCGMH3wOP5bVHbOye",
    "confirmation_method": "automatic",
    "created": 1660420127,
    "currency": "usd",
    "customer": "cus_MEu8lc7NZySWFU",
    "description": None,
    "invoice": None,
    "metadata": {},
    "on_behalf_of": None,
    "payment_method": "pm_1LWQKSHg7k0wiFizEbK2sgEZ",
    "payment_method_options": {
        "card": {
            "installments": None,
            "mandate_options": None,
            "network": None,
            "request_three_d_secure": "automatic",
        }
    },
    "payment_method_types": ["card"],
    "processing": None,
    "receipt_email": None,
    "review": None,
    "setup_future_usage": None,
    "shipping": None,
    "source": None,
    "statement_descriptor": None,
    "statement_descriptor_suffix": None,
    "transfer_data": None,
    "transfer_group": None,
}

PAYOUT_DISABLED_ACCT = {
    "id": "acct_1LPuDbHg7k0wiFiz",
    "object": "account",
    "business_profile": {
        "mcc": "5734",
        "name": "Mocha Jump INC.",
        "product_description": "Webcomics hosting platform\n",
        "support_address": {
            "city": "Austin",
            "country": "US",
            "line1": "3400 Harmon Avenue",
            "line2": None,
            "postal_code": "78705",
            "state": "TX",
        },
        "support_email": None,
        "support_phone": "+17132912159",
        "support_url": None,
        "url": "mochajump.com",
    },
    "business_type": "company",
    "capabilities": {
        "card_payments": {"requested": True},
        "transfers": {"requested": True},
    },
    "charges_enabled": False,
    "company": {
        "address": {
            "city": "Austin",
            "country": "US",
            "line1": "3400 Harmon Avenue",
            "line2": "APT 224",
            "postal_code": "78705",
            "state": "TX",
        },
        "directors_provided": False,
        "executives_provided": True,
        "name": "Mocha Jump INC.",
        "owners_provided": True,
        "phone": "+17132912159",
        "structure": "private_corporation",
        "tax_id_provided": True,
        "verification": {
            "document": {
                "back": None,
                "details": None,
                "details_code": None,
                "front": None,
            }
        },
    },
    "controller": {"type": "account"},
    "country": "US",
    "created": 1658866743,
    "default_currency": "usd",
    "details_submitted": True,
    "email": "jenny.rosen@example.com",
    "external_accounts": {
        "object": "list",
        "data": [
            {
                "id": "ba_1LUZkIHg7k0wiFizhNl692ha",
                "object": "bank_account",
                "account": "acct_1LPuDbHg7k0wiFiz",
                "account_holder_name": None,
                "account_holder_type": None,
                "account_type": None,
                "available_payout_methods": ["standard"],
                "bank_name": "COLUMN NA BREX",
                "country": "US",
                "currency": "usd",
                "default_for_currency": True,
                "fingerprint": "bGJQVCGK4omt5mgx",
                "last4": "2993",
                "metadata": {},
                "routing_number": "121145349",
                "status": "new",
            }
        ],
        "has_more": False,
        "url": "/v1/accounts/acct_1LPuDbHg7k0wiFiz/external_accounts",
    },
    "future_requirements": {
        "alternatives": [],
        "current_deadline": None,
        "currently_due": [],
        "disabled_reason": None,
        "errors": [],
        "eventually_due": [],
        "past_due": [],
        "pending_verification": [],
    },
    "metadata": {},
    "payouts_enabled": True,
    "requirements": {
        "alternatives": [],
        "current_deadline": None,
        "currently_due": [],
        "disabled_reason": None,
        "errors": [],
        "eventually_due": [],
        "past_due": [],
        "pending_verification": [],
    },
    "settings": {
        "bacs_debit_payments": {},
        "branding": {
            "icon": "file_1LXYIbHg7k0wiFizfUVqdqMD",
            "logo": "file_1LVo0XHg7k0wiFizHvKsH0gE",
            "primary_color": "#525f7f",
            "secondary_color": "#0074d4",
        },
        "card_issuing": {"tos_acceptance": {"date": None, "ip": None}},
        "card_payments": {
            "decline_on": {"avs_failure": False, "cvc_failure": False},
            "statement_descriptor_prefix": "MOCHAJUMP",
            "statement_descriptor_prefix_kanji": None,
            "statement_descriptor_prefix_kana": None,
        },
        "dashboard": {"display_name": "Mochajump", "timezone": "America/Chicago"},
        "payments": {
            "statement_descriptor": "MOCHAJUMP.COM",
            "statement_descriptor_kana": None,
            "statement_descriptor_kanji": None,
        },
        "payouts": {
            "debit_negative_balances": True,
            "schedule": {"delay_days": 2, "interval": "manual"},
            "statement_descriptor": None,
        },
        "sepa_debit_payments": {},
    },
    "tos_acceptance": {
        "date": 1659979966,
        "ip": "104.185.180.194",
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    },
    "type": "custom",
}

PAYOUT_ENABLED_ACCT = {
    "id": "acct_1LPuDbHg7k0wiFiz",
    "object": "account",
    "business_profile": {
        "mcc": "5734",
        "name": "Mocha Jump INC.",
        "product_description": "Webcomics hosting platform\n",
        "support_address": {
            "city": "Austin",
            "country": "US",
            "line1": "3400 Harmon Avenue",
            "line2": None,
            "postal_code": "78705",
            "state": "TX",
        },
        "support_email": None,
        "support_phone": "+17132912159",
        "support_url": None,
        "url": "mochajump.com",
    },
    "business_type": "company",
    "capabilities": {
        "card_payments": {"requested": True},
        "transfers": {"requested": True},
    },
    "charges_enabled": True,
    "company": {
        "address": {
            "city": "Austin",
            "country": "US",
            "line1": "3400 Harmon Avenue",
            "line2": "APT 224",
            "postal_code": "78705",
            "state": "TX",
        },
        "directors_provided": False,
        "executives_provided": True,
        "name": "Mocha Jump INC.",
        "owners_provided": True,
        "phone": "+17132912159",
        "structure": "private_corporation",
        "tax_id_provided": True,
        "verification": {
            "document": {
                "back": None,
                "details": None,
                "details_code": None,
                "front": None,
            }
        },
    },
    "controller": {"type": "account"},
    "country": "US",
    "created": 1658866743,
    "default_currency": "usd",
    "details_submitted": True,
    "email": "jenny.rosen@example.com",
    "external_accounts": {
        "object": "list",
        "data": [
            {
                "id": "ba_1LUZkIHg7k0wiFizhNl692ha",
                "object": "bank_account",
                "account": "acct_1LPuDbHg7k0wiFiz",
                "account_holder_name": None,
                "account_holder_type": None,
                "account_type": None,
                "available_payout_methods": ["standard"],
                "bank_name": "COLUMN NA BREX",
                "country": "US",
                "currency": "usd",
                "default_for_currency": True,
                "fingerprint": "bGJQVCGK4omt5mgx",
                "last4": "2993",
                "metadata": {},
                "routing_number": "121145349",
                "status": "new",
            }
        ],
        "has_more": False,
        "url": "/v1/accounts/acct_1LPuDbHg7k0wiFiz/external_accounts",
    },
    "future_requirements": {
        "alternatives": [],
        "current_deadline": None,
        "currently_due": [],
        "disabled_reason": None,
        "errors": [],
        "eventually_due": [],
        "past_due": [],
        "pending_verification": [],
    },
    "metadata": {},
    "payouts_enabled": True,
    "requirements": {
        "alternatives": [],
        "current_deadline": None,
        "currently_due": [],
        "disabled_reason": None,
        "errors": [],
        "eventually_due": [],
        "past_due": [],
        "pending_verification": [],
    },
    "settings": {
        "bacs_debit_payments": {},
        "branding": {
            "icon": "file_1LXYIbHg7k0wiFizfUVqdqMD",
            "logo": "file_1LVo0XHg7k0wiFizHvKsH0gE",
            "primary_color": "#525f7f",
            "secondary_color": "#0074d4",
        },
        "card_issuing": {"tos_acceptance": {"date": None, "ip": None}},
        "card_payments": {
            "decline_on": {"avs_failure": False, "cvc_failure": False},
            "statement_descriptor_prefix": "MOCHAJUMP",
            "statement_descriptor_prefix_kanji": None,
            "statement_descriptor_prefix_kana": None,
        },
        "dashboard": {"display_name": "Mochajump", "timezone": "America/Chicago"},
        "payments": {
            "statement_descriptor": "MOCHAJUMP.COM",
            "statement_descriptor_kana": None,
            "statement_descriptor_kanji": None,
        },
        "payouts": {
            "debit_negative_balances": True,
            "schedule": {"delay_days": 2, "interval": "manual"},
            "statement_descriptor": None,
        },
        "sepa_debit_payments": {},
    },
    "tos_acceptance": {
        "date": 1659979966,
        "ip": "104.185.180.194",
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ",
    },
    "type": "custom",
}
