exclude: '^$'
default_language_version:
    python: python3
repos:
- repo: https://github.com/PyCQA/flake8
  rev: 3.7.8
  hooks:
  - id: flake8
    exclude: "/migrations"
- repo: https://github.com/timothycrosley/isort
  rev: 5.6.4
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    exclude: "/migrations"
- repo: https://github.com/pycqa/pylint
  rev: pylint-2.4.4
  hooks:
  - id: pylint
- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
  - id: bandit
    exclude: "/test_"
    args:
      - "-c=.bandit.yaml"