# Generated by Django 3.2.15 on 2022-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_remove_wallet_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usd_value',
            field=models.FloatField(default=0),
        ),
    ]
