# Generated by Django 3.2.15 on 2022-08-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moka_profile', '0008_profile_high_status_for_early_adopters'),
        ('money', '0003_wallet_usd_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='moka_profile.mokaprofile'),
        ),
    ]
