# Generated by Django 3.2.15 on 2022-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_alter_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='stripe_connect_account',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
