# Generated by Django 3.2.15 on 2022-08-19 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moka_profile', '0008_profile_high_status_for_early_adopters'),
        ('money', '0005_wallet_stripe_connect_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('DEPOSIT', 'Deposit'), ('PURCHASE', 'Purchase')], max_length=50)),
                ('coin_amount', models.PositiveBigIntegerField()),
                ('usd_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_transactions', to='moka_profile.mokaprofile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_transactions', to='moka_profile.mokaprofile')),
            ],
        ),
    ]
