# Generated by Django 3.2.15 on 2022-08-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='monthly_profit_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='monthly_profit_usd_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='payout_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='payout_usd_value',
            field=models.FloatField(default=0),
        ),
    ]
