# Generated by Django 3.2.14 on 2022-08-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedCollection',
        ),
    ]
