# Generated by Django 3.2.15 on 2022-10-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_delete_purchasedcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcollection',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='workcollection',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workcollection',
            name='series',
        ),
        migrations.DeleteModel(
            name='LikedCollection',
        ),
        migrations.DeleteModel(
            name='WorkCollection',
        ),
    ]
