# Generated by Django 3.2.13 on 2022-07-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='url',
        ),
    ]
