# Generated by Django 3.2.14 on 2022-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20220706_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='height',
        ),
        migrations.RemoveField(
            model_name='page',
            name='width',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='height',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='width',
        ),
        migrations.AddField(
            model_name='page',
            name='external_id',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='storage',
            field=models.CharField(choices=[('CLOUDFLARE_IMAGES', 'Cloudflare Images')], default='CLOUDFLARE_IMAGES', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='external_id',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='storage',
            field=models.CharField(choices=[('CLOUDFLARE_IMAGES', 'Cloudflare Images')], default='CLOUDFLARE_IMAGES', max_length=100),
            preserve_default=False,
        ),
    ]
