# Generated by Django 3.2.14 on 2022-07-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moka_profile', '0003_alter_mokaprofile_description'),
        ('image', '0005_auto_20220713_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', related_query_name='page', to='moka_profile.mokaprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owning_thumbnails', related_query_name='owning_thumbnail', to='moka_profile.mokaprofile'),
            preserve_default=False,
        ),
    ]
