# Generated by Django 3.2.14 on 2022-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20220715_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='storage',
            field=models.CharField(choices=[('CLOUDFLARE_IMAGES', 'Cloudflare Images'), ('GOOGLE_CLOUD_STORAGE', 'Google Cloud Storage')], max_length=100),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='storage',
            field=models.CharField(choices=[('CLOUDFLARE_IMAGES', 'Cloudflare Images'), ('GOOGLE_CLOUD_STORAGE', 'Google Cloud Storage')], max_length=100),
        ),
    ]
