# Generated by Django 3.2.13 on 2022-06-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_page'),
        ('moka_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mokaprofile',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.thumbnail'),
        ),
    ]
