# Generated by Django 3.2.14 on 2022-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moka_profile', '0006_alter_mokaprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mokaprofile',
            name='payout_status',
            field=models.CharField(choices=[('HIGH_VALUE', 'High Value'), ('REGULAR', 'Regular')], default='REGULAR', max_length=50),
        ),
    ]
