# Generated by Django 3.2.15 on 2022-08-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moka_profile', '0009_createsuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mokaprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
