#!/usr/bin/env bash
set -euo pipefail

apt-get update

apt-get -y upgrade

apt-get install -y --no-install-recommends curl netcat
apt-get install -y libpq-dev python3-dev

apt-get clean
rm -rf /var/lib/apt/lists/*
