# Generated by Django 3.2.13 on 2022-06-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moka_profile', '0001_initial'),
        ('series', '0001_initial'),
        ('image', '0002_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PUBLIC', 'Public'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], max_length=10)),
                ('episode_number', models.PositiveIntegerField()),
                ('likes', models.ManyToManyField(related_name='liked_episodes', to='moka_profile.MokaProfile')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', related_query_name='episode', to='series.series')),
                ('thumbnail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('PUBLIC', 'Public'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', related_query_name='page', to='episode.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
