# Generated by Django 3.2.13 on 2022-06-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_auto_20220611_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
