# Generated by Django 3.2.14 on 2022-08-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moka_profile', '0004_mokaprofile_display_name'),
        ('episode', '0003_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episode.episode')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moka_profile.mokaprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='likes',
        ),
        migrations.AddField(
            model_name='episode',
            name='likes',
            field=models.ManyToManyField(related_name='liked_episodes', through='episode.LikeEpisode', to='moka_profile.MokaProfile'),
        ),
    ]
