# Generated by Django 3.2.14 on 2022-08-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0004_auto_20220802_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='trend_score',
            field=models.FloatField(default=0),
        ),
    ]
