# Generated by Django 3.2.14 on 2022-08-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0005_episode_trend_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_scroll_view',
            field=models.BooleanField(default=False),
        ),
    ]
