# Generated by Django 3.2.14 on 2022-08-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0006_episode_is_scroll_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='release_scheduled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRERELEASE', 'Pre Release'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], max_length=10),
        ),
    ]
