# Generated by Django 3.2.15 on 2022-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0009_episode_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
