# Generated by Django 3.2.13 on 2022-06-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moka_profile', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_series', to='moka_profile.mokaprofile'),
        ),
    ]
