# Generated by Django 3.2.15 on 2022-08-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_alter_series_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': "Series'"},
        ),
        migrations.AddField(
            model_name='series',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
